//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.Controls.Tests {
    
    
    public partial class UpdateSelectedTesterTypes {
        
        /// <summary>
        /// scUpdateSelectedTesterTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.ScriptLiteral scUpdateSelectedTesterTypes;
        
        /// <summary>
        /// cphNoResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder cphNoResults;
        
        /// <summary>
        /// afUpdateSelectedTesterTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.AsyncForm afUpdateSelectedTesterTypes;
        
        /// <summary>
        /// rptTesterTypesRpt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptTesterTypesRpt;
        
        /// <summary>
        /// ihStatus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihStatus;
        
        /// <summary>
        /// ihTesterTypeID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTesterTypeID;
        
        /// <summary>
        /// ihTriggerID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTriggerID;
        
        /// <summary>
        /// ihTestID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTestID;
    }
}
