//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.ControlLoaders.Triggers {
    
    
    public partial class UpdateOrCreateTriggerControlLoader {
        
        /// <summary>
        /// Triggers_UpdateOrCreateTrigger control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Triggers.UpdateOrCreateTrigger Triggers_UpdateOrCreateTrigger;
    }
}
