//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySpace.MSFast.Automation.Resources.Web.Application.Controls.Triggers.Browse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TriggersList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TriggersList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySpace.MSFast.Automation.Resources.Web.Application.Controls.Triggers.Browse.TriggersList", typeof(TriggersList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trigger.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Triggered.
        /// </summary>
        internal static string lasttriggered {
            get {
                return ResourceManager.GetString("lasttriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Triggers Found....
        /// </summary>
        internal static string noresults {
            get {
                return ResourceManager.GetString("noresults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trigger.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string trigger {
            get {
                return ResourceManager.GetString("trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Trigger.
        /// </summary>
        internal static string trigger_type_manual {
            get {
                return ResourceManager.GetString("trigger_type_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time-Based Trigger.
        /// </summary>
        internal static string trigger_type_time {
            get {
                return ResourceManager.GetString("trigger_type_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n/a.
        /// </summary>
        internal static string trigger_type_unknown {
            get {
                return ResourceManager.GetString("trigger_type_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Name.
        /// </summary>
        internal static string triggername {
            get {
                return ResourceManager.GetString("triggername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Type.
        /// </summary>
        internal static string triggertype {
            get {
                return ResourceManager.GetString("triggertype", resourceCulture);
            }
        }
    }
}
