//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.Controls.Triggers {
    
    
    public partial class UpdateTriggerToTestAndTesterType {
        
        /// <summary>
        /// siJLoadControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.StaticFileInclude siJLoadControl;
        
        /// <summary>
        /// slUpdateTriggerToTestAndTesterType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.StyleLiteral slUpdateTriggerToTestAndTesterType;
        
        /// <summary>
        /// scUpdateTriggerToTestAndTesterType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.ScriptLiteral scUpdateTriggerToTestAndTesterType;
        
        /// <summary>
        /// Tests_TestsPaging_SelectedTests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Tests.Browse.TestsPaging Tests_TestsPaging_SelectedTests;
        
        /// <summary>
        /// Tests_UpdateSelectedTesterTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Tests.UpdateSelectedTesterTypes Tests_UpdateSelectedTesterTypes;
        
        /// <summary>
        /// Tests_TestsPaging_AllTests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Tests.Browse.TestsPaging Tests_TestsPaging_AllTests;
    }
}
