//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application {
    
    
    public partial class _Default {
        
        /// <summary>
        /// slMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.StyleLiteral slMain;
        
        /// <summary>
        /// hrefLatestResults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Tags.Href hrefLatestResults;
        
        /// <summary>
        /// hrefManageTests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Tags.Href hrefManageTests;
        
        /// <summary>
        /// hrefManageTestBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Tags.Href hrefManageTestBox;
        
        /// <summary>
        /// hrefManageManageTriggers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Tags.Href hrefManageManageTriggers;
    }
}
