//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.Controls.Collectors {
    
    
    public partial class UpdateCollectorsConfiguration {
        
        /// <summary>
        /// slUpdateCollectorsConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.StyleLiteral slUpdateCollectorsConfiguration;
        
        /// <summary>
        /// scUpdateCollectorsConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.ScriptLiteral scUpdateCollectorsConfiguration;
        
        /// <summary>
        /// afUpdateCollectorsConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.AsyncForm afUpdateCollectorsConfiguration;
        
        /// <summary>
        /// ihTestID_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTestID_Update;
        
        /// <summary>
        /// ihTesterTypeID_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTesterTypeID_Update;
        
        /// <summary>
        /// ihTriggerID_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTriggerID_Update;
        
        /// <summary>
        /// ihKey_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihKey_Update;
        
        /// <summary>
        /// ihVal_Update control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihVal_Update;
        
        /// <summary>
        /// afRemoveCollectorsConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.AsyncForm afRemoveCollectorsConfiguration;
        
        /// <summary>
        /// ihTestID_Remove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTestID_Remove;
        
        /// <summary>
        /// ihTesterTypeID_Remove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTesterTypeID_Remove;
        
        /// <summary>
        /// ihTriggerID_Remove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihTriggerID_Remove;
        
        /// <summary>
        /// ihKey_Remove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Forms.InputHidden ihKey_Remove;
        
        /// <summary>
        /// rptConfiguration control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptConfiguration;
    }
}
