//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.Pages.Tests {
    
    
    public partial class ShowTestDetails {
        
        /// <summary>
        /// phValidTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phValidTest;
        
        /// <summary>
        /// sbTestURL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.Style.SubTitle sbTestURL;
        
        /// <summary>
        /// Results_ResultsDisplayAndFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Results.ResultsDisplayAndFilter Results_ResultsDisplayAndFilter;
        
        /// <summary>
        /// phInvalidTest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phInvalidTest;
    }
}
