//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDika.Web.Application.Controls.Tests.Browse {
    
    
    public partial class TesterTypesPaging {
        
        /// <summary>
        /// bfBrowseTesterTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EYF.Web.Controls.Common.BrowseForm bfBrowseTesterTypes;
        
        /// <summary>
        /// Tests_TesterTypesList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BDika.Web.Application.Controls.Tests.Browse.TesterTypesList Tests_TesterTypesList;
    }
}
